/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"



volatile uint8 task1_Tick = 0;
volatile uint8 task2_Tick = 0;
volatile uint8 task3_Tick = 0;
volatile uint8 task4_Tick = 0;

int main(void)
{
	GPIO_u8PinInit(&BUILT_IN_LED);
	GPIO_u8PinInit(&LED2);
	GPIO_u8PinInit(&LED3);
	GPIO_u8PinInit(&LED4);

	Enable_FaultException();
	SYSTICK_Init();
	Stack_InitScheduler_Stack(SCHED_TASK_STACK);
	Stack_InitTasks_Stack();
	ChangeToPSP();

	Task1_Handler();

	/* Loop forever */
	for(;;)
	{
		//TOG_BIT(Os_Tick, 1);
		//GPIO_u8TogglePinValue(PORTA, PIN5);
		//SYSTICK_Delay_ms(1);
	}
}



void Task1_Handler(){
	while(1){
		TOG_BIT(task1_Tick, 1);
		OS_TaskDelay(3000);
		//printf("Task1 Handler \n");
		//TOG_BIT((GPIOA->ODR), 6);
	}

}

void Task2_Handler(){
	while(1){
		TOG_BIT(task2_Tick, 1);
		OS_TaskDelay(3000);

		//printf("Task2 Handler \n");
		//TOG_BIT((GPIOA->ODR), 7);
	}


}

void Task3_Handler(){
	while(1){
		TOG_BIT(task3_Tick, 1);
		OS_TaskDelay(3000);
		//printf("Task3 Handler \n");
		//TOG_BIT((GPIOB->ODR), 6);
	}

}

