name: Build RTOS Scheduler

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi make cmake ninja-build || \
          (wget https://github.com/ninja-build/ninja/releases/latest/download/ninja-linux.zip && \
          sudo unzip ninja-linux.zip -d /usr/local/bin/ && \
          sudo chmod +x /usr/local/bin/ninja)

      - name: Build Stm32Cube Project
        run: |
          # Change directory to RTOS_Scheduler/Debug
          cd RTOS_Scheduler/Debug
          
          # Run make to build the project
          make -j16 all

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rtos_scheduler_firmware
          path: RTOS_Scheduler/Debug/RTOS_Scheduler.hex
